//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assigns
    {
        public int AssignId { get; set; }
        public int HealthcareAssistantId { get; set; }
        public int PatientId { get; set; }
    
        public virtual HealthcareAssistants HealthcareAssistants { get; set; }
        public virtual Patients Patients { get; set; }

        public void GetData()
        {
            Console.WriteLine("Enter Assistant Id : ");
            HealthcareAssistantId = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter Patient Id : ");
            PatientId= Convert.ToInt32(Console.ReadLine());
        }
    }
}
