//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosises
    {
        public int DiagnosisId { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public string DiagnosisDetails { get; set; }
    
        public virtual Diagnosises Diagnosises1 { get; set; }
        public virtual Diagnosises Diagnosises2 { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
        public void GetData()
        {
            Console.WriteLine("Enter Doctor ID: ");
            this.DoctorId = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter Patient ID: ");
            PatientId = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter Diagnosis Details : ");
            DiagnosisDetails = Console.ReadLine();
        }
    }
    
}
