//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctors()
        {
            this.Diagnosises = new HashSet<Diagnosises>();
            this.Prescribes = new HashSet<Prescribes>();
        }
    
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string DoctorPhoneNumber { get; set; }
        public string DoctorGender { get; set; }
        public string DoctorQualification { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosises> Diagnosises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribes> Prescribes { get; set; }
        public void GetData()
        {
            Console.WriteLine("Enter Doctor Name : ");
            DoctorName = Console.ReadLine();
            Console.WriteLine("Enter Doctor Gender : ");
            DoctorGender = Console.ReadLine();
            Console.WriteLine("Enter Doctor Qualification :");
            DoctorQualification = Console.ReadLine();
            Console.WriteLine("Enter Department Id");
            DepartmentId = Convert.ToInt32(Console.ReadLine());
           

        }
        public void List()
        {
            var db = new HospitalDbEntities();
            var doctorList = db.Doctors;
            try
            {
                Console.WriteLine("Name \t Gender Degree \t Mobile Number");
                foreach (var doctor in doctorList)
                {
                    Console.WriteLine(doctor.DoctorName + "    " + doctor.DoctorGender + "      " + doctor.DoctorQualification+ "     " + doctor.DoctorPhoneNumber);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("There are no patients");
            }
        }
    }
}
