//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drugs()
        {
            this.DrugTimes = new HashSet<DrugTimes>();
        }
    
        public int DrugId { get; set; }
        public string DrugName { get; set; }
        public string DrugDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugTimes> DrugTimes { get; set; }

        public void GetData()
        {
            Console.WriteLine("Enter Drug Name :");
            DrugName = Console.ReadLine();
            Console.WriteLine("Enter Drug Description : ");
            DrugDescription = Console.ReadLine();
        }
    }
}
