//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthcareAssistants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthcareAssistants()
        {
            this.Assigns = new HashSet<Assigns>();
        }
    
        public int HealthcareAssistantId { get; set; }
        public string HealthcareAssistantName { get; set; }
        public string HealthcareAssistantQualification { get; set; }
        public string HealthcareAssistantGender { get; set; }
        public int DepartmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assigns> Assigns { get; set; }
        public virtual Departments Departments { get; set; }

        public void GetData()
        {
            Console.WriteLine("Enter Assistant Name : ");
            HealthcareAssistantName = Console.ReadLine();
            Console.WriteLine("Enter Assistant Gender : ");
            HealthcareAssistantGender = Console.ReadLine();
            Console.WriteLine("Enter Assistant Qualification :");
            HealthcareAssistantQualification = Console.ReadLine();
            Console.WriteLine("Enter Department Id");
            DepartmentId = Convert.ToInt32(Console.ReadLine());


        }


    }

}
