//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDbEntities : DbContext
    {
        public HospitalDbEntities()
            : base("name=HospitalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assigns> Assigns { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Diagnosises> Diagnosises { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<DrugTimes> DrugTimes { get; set; }
        public virtual DbSet<HealthcareAssistants> HealthcareAssistants { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Prescribes> Prescribes { get; set; }
    }
}
