//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescribes
    {
        public int PrescribeId { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public string PrescribeDetail { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
        public void GetData()
        {
            Console.WriteLine("Enter PatientId : ");
            PatientId = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter DoctorId : ");
            DoctorId = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter Prescription : ");
            PrescribeDetail = Console.ReadLine();

        
        }
    }

}
