//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyManufacturerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.OrderInvoices = new HashSet<OrderInvoice>();
        }
    
        public int OfferId { get; set; }
        public int MinAmount { get; set; }
        public int Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInvoice> OrderInvoices { get; set; }

        public void GetData()
        {
            Console.WriteLine("Enter Minimum Amount");
            MinAmount = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter Discount");
            Discount = Convert.ToInt32(Console.ReadLine());
        }

    }
}
