//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyManufacturerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plant()
        {
            this.Toys = new HashSet<Toy>();
        }
    
        public int PlantId { get; set; }
        public string PlantName { get; set; }
        public string PlantAddress { get; set; }
        public string PlantMobileNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toy> Toys { get; set; }

        public void GetData()
        {
            Console.WriteLine("Enter Plant Name : ");
            PlantName = Console.ReadLine();
            Console.WriteLine("Enter Plant Address : ");
            PlantAddress = Console.ReadLine();
            Console.WriteLine("Enter Plant Mobile Number");
            PlantMobileNumber = Console.ReadLine();
        }
    }
}
