//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyManufacturerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toy()
        {
            this.OrderInvoices = new HashSet<OrderInvoice>();
        }
    
        public int ToyId { get; set; }
        public string ToyName { get; set; }
        public int ToyPrice { get; set; }
        public string ToyDetail { get; set; }
        public int PlantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInvoice> OrderInvoices { get; set; }
        public virtual Plant Plant { get; set; }

        public void GetData()
        {
            Console.WriteLine("Enter Toy Name : ");
            ToyName = Console.ReadLine();
            Console.WriteLine("Enter Toy Price : ");
            ToyPrice = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter Toy Detail :");
            ToyDetail = Console.ReadLine();
            Console.WriteLine("Enter Plant Id");
            PlantId = Convert.ToInt32(Console.ReadLine());

        }

        public void List()
        {
            var dbContext = new ToyManufacturerDbEntities();

            Console.WriteLine("Toy Id \tName \t Price \t Detail \t PlantId");
            foreach (var toy in dbContext.Toys)
            {
                Console.WriteLine(toy.ToyId + toy.ToyName + toy.ToyPrice + toy.ToyDetail + toy.PlantId);
            }
        }
    }
}
