//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyManufacturerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrderDetail
    {
        public string ToyName { get; set; }
        public System.DateTime OrderDetailDate { get; set; }
        public int FinalPrice { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerMobileNumber { get; set; }
        public string AddressLocation { get; set; }
        public string City { get; set; }
        public int Pincode { get; set; }
        public int OfferId { get; set; }
        public int OrderDetailId { get; set; }
    }
}
